name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Получаем код
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Ставим Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Проверка
      - name: Print Node version
        run: node -v

      # 4️⃣ Устанавливаем зависимости
      - name: Установить зависимости
        run: npm install

      # 5️⃣ Запускаем тесты
      - name: Запуск тестов
        run: npm test